version: "3.7"

services:
  api:
    image: node:18.17.1-alpine3.18
    container_name: talenttrout-api
    command: sh -c "chmod -R 777 /usr/src/uploads; npm start;"
    working_dir: /usr/src/app
    volumes:
      - ./server/:/usr/src/app
      - talenttrout-uploads:/usr/src/uploads
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev.api
      - ./.env.dev.db
    depends_on:
      - mongo

  client:
    image: node:18.17.1-alpine3.18
    container_name: talenttrout-client
    command: sh -c "chmod -R 777 /usr/src/uploads; npm start"
    working_dir: /usr/src/app
    volumes:
      - ./client/:/usr/src/app/
      - talenttrout-uploads:/usr/src/uploads
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev.client
    depends_on:
      - api

  
  mongo:
    image: mongo:5.0
    container_name: talenttrout-mongo
    
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - talenttrout-mongo:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: talenttrout-mexpress
    volumes:
      - talenttrout-mexpress:/var/lib/mexpress
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: always
    ports:
      - "8081:8081"



volumes:
  talenttrout-uploads:
  talenttrout-mongo:
  talenttrout-mexpress:
